/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LkuCodeType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LkuCode
 */
public class LkuCodeTest {
    private final LkuCode model = new LkuCode();

    /**
     * Model tests for LkuCode
     */
    @Test
    public void testLkuCode() {
        // TODO: test LkuCode
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'lkuCodeId'
     */
    @Test
    public void lkuCodeIdTest() {
        // TODO: test lkuCodeId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'lkuCodeTypeId'
     */
    @Test
    public void lkuCodeTypeIdTest() {
        // TODO: test lkuCodeTypeId
    }

    /**
     * Test the property 'lkuCodeType'
     */
    @Test
    public void lkuCodeTypeTest() {
        // TODO: test lkuCodeType
    }

    /**
     * Test the property 'displayOrder'
     */
    @Test
    public void displayOrderTest() {
        // TODO: test displayOrder
    }

}
