/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LkuCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Location
 */
public class LocationTest {
    private final Location model = new Location();

    /**
     * Model tests for Location
     */
    @Test
    public void testLocation() {
        // TODO: test Location
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'locationType'
     */
    @Test
    public void locationTypeTest() {
        // TODO: test locationType
    }

    /**
     * Test the property 'locationTypeId'
     */
    @Test
    public void locationTypeIdTest() {
        // TODO: test locationTypeId
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stateTerritoryName'
     */
    @Test
    public void stateTerritoryNameTest() {
        // TODO: test stateTerritoryName
    }

    /**
     * Test the property 'zip'
     */
    @Test
    public void zipTest() {
        // TODO: test zip
    }

    /**
     * Test the property 'zip2'
     */
    @Test
    public void zip2Test() {
        // TODO: test zip2
    }

    /**
     * Test the property 'naLocation'
     */
    @Test
    public void naLocationTest() {
        // TODO: test naLocation
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'countryId'
     */
    @Test
    public void countryIdTest() {
        // TODO: test countryId
    }

    /**
     * Test the property 'shortLocationString'
     */
    @Test
    public void shortLocationStringTest() {
        // TODO: test shortLocationString
    }

}
