/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelFile
 */
public class ModelFileTest {
    private final ModelFile model = new ModelFile();

    /**
     * Model tests for ModelFile
     */
    @Test
    public void testModelFile() {
        // TODO: test ModelFile
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'fileSize'
     */
    @Test
    public void fileSizeTest() {
        // TODO: test fileSize
    }

    /**
     * Test the property 'fileExtension'
     */
    @Test
    public void fileExtensionTest() {
        // TODO: test fileExtension
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

}
