/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Organization;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrganizationGetListByNameResponse
 */
public class OrganizationGetListByNameResponseTest {
    private final OrganizationGetListByNameResponse model = new OrganizationGetListByNameResponse();

    /**
     * Model tests for OrganizationGetListByNameResponse
     */
    @Test
    public void testOrganizationGetListByNameResponse() {
        // TODO: test OrganizationGetListByNameResponse
    }

    /**
     * Test the property 'organizations'
     */
    @Test
    public void organizationsTest() {
        // TODO: test organizations
    }

}
