/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LkuCode;
import com.konfigthis.client.model.Location;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Organization
 */
public class OrganizationTest {
    private final Organization model = new Organization();

    /**
     * Model tests for Organization
     */
    @Test
    public void testOrganization() {
        // TODO: test Organization
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'acronym'
     */
    @Test
    public void acronymTest() {
        // TODO: test acronym
    }

    /**
     * Test the property 'fax'
     */
    @Test
    public void faxTest() {
        // TODO: test fax
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'organizationName'
     */
    @Test
    public void organizationNameTest() {
        // TODO: test organizationName
    }

    /**
     * Test the property 'organizationType'
     */
    @Test
    public void organizationTypeTest() {
        // TODO: test organizationType
    }

    /**
     * Test the property 'organizationTypeId'
     */
    @Test
    public void organizationTypeIdTest() {
        // TODO: test organizationTypeId
    }

    /**
     * Test the property 'parentOrganizationId'
     */
    @Test
    public void parentOrganizationIdTest() {
        // TODO: test parentOrganizationId
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'replacementOrganizationId'
     */
    @Test
    public void replacementOrganizationIdTest() {
        // TODO: test replacementOrganizationId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'naOrganization'
     */
    @Test
    public void naOrganizationTest() {
        // TODO: test naOrganization
    }

    /**
     * Test the property 'external'
     */
    @Test
    public void externalTest() {
        // TODO: test external
    }

    /**
     * Test the property 'linkCount'
     */
    @Test
    public void linkCountTest() {
        // TODO: test linkCount
    }

    /**
     * Test the property 'murepUnitId'
     */
    @Test
    public void murepUnitIdTest() {
        // TODO: test murepUnitId
    }

    /**
     * Test the property 'ein'
     */
    @Test
    public void einTest() {
        // TODO: test ein
    }

    /**
     * Test the property 'uei'
     */
    @Test
    public void ueiTest() {
        // TODO: test uei
    }

    /**
     * Test the property 'dunsNumber'
     */
    @Test
    public void dunsNumberTest() {
        // TODO: test dunsNumber
    }

    /**
     * Test the property 'msiData'
     */
    @Test
    public void msiDataTest() {
        // TODO: test msiData
    }

    /**
     * Test the property 'setAsideData'
     */
    @Test
    public void setAsideDataTest() {
        // TODO: test setAsideData
    }

}
