/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Organization;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Program
 */
public class ProgramTest {
    private final Program model = new Program();

    /**
     * Model tests for Program
     */
    @Test
    public void testProgram() {
        // TODO: test Program
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'programId'
     */
    @Test
    public void programIdTest() {
        // TODO: test programId
    }

    /**
     * Test the property 'acronym'
     */
    @Test
    public void acronymTest() {
        // TODO: test acronym
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'parentProgram'
     */
    @Test
    public void parentProgramTest() {
        // TODO: test parentProgram
    }

    /**
     * Test the property 'parentProgramId'
     */
    @Test
    public void parentProgramIdTest() {
        // TODO: test parentProgramId
    }

    /**
     * Test the property 'responsibleMd'
     */
    @Test
    public void responsibleMdTest() {
        // TODO: test responsibleMd
    }

    /**
     * Test the property 'responsibleMdId'
     */
    @Test
    public void responsibleMdIdTest() {
        // TODO: test responsibleMdId
    }

}
