/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Contact;
import com.konfigthis.client.model.LibraryItem;
import com.konfigthis.client.model.LkuCode;
import com.konfigthis.client.model.Location;
import com.konfigthis.client.model.Organization;
import com.konfigthis.client.model.Program;
import com.konfigthis.client.model.TaxonomyNode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Project
 */
public class ProjectTest {
    private final Project model = new Project();

    /**
     * Model tests for Project
     */
    @Test
    public void testProject() {
        // TODO: test Project
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'acronym'
     */
    @Test
    public void acronymTest() {
        // TODO: test acronym
    }

    /**
     * Test the property 'statusDescription'
     */
    @Test
    public void statusDescriptionTest() {
        // TODO: test statusDescription
    }

    /**
     * Test the property 'benefits'
     */
    @Test
    public void benefitsTest() {
        // TODO: test benefits
    }

    /**
     * Test the property 'startDateString'
     */
    @Test
    public void startDateStringTest() {
        // TODO: test startDateString
    }

    /**
     * Test the property 'endDateString'
     */
    @Test
    public void endDateStringTest() {
        // TODO: test endDateString
    }

    /**
     * Test the property 'startTrl'
     */
    @Test
    public void startTrlTest() {
        // TODO: test startTrl
    }

    /**
     * Test the property 'currentTrl'
     */
    @Test
    public void currentTrlTest() {
        // TODO: test currentTrl
    }

    /**
     * Test the property 'endTrl'
     */
    @Test
    public void endTrlTest() {
        // TODO: test endTrl
    }

    /**
     * Test the property 'primaryTaxonomyNodes'
     */
    @Test
    public void primaryTaxonomyNodesTest() {
        // TODO: test primaryTaxonomyNodes
    }

    /**
     * Test the property 'additionalTaxonomyNodes'
     */
    @Test
    public void additionalTaxonomyNodesTest() {
        // TODO: test additionalTaxonomyNodes
    }

    /**
     * Test the property 'destinations'
     */
    @Test
    public void destinationsTest() {
        // TODO: test destinations
    }

    /**
     * Test the property 'program'
     */
    @Test
    public void programTest() {
        // TODO: test program
    }

    /**
     * Test the property 'responsibleMd'
     */
    @Test
    public void responsibleMdTest() {
        // TODO: test responsibleMd
    }

    /**
     * Test the property 'leadOrganization'
     */
    @Test
    public void leadOrganizationTest() {
        // TODO: test leadOrganization
    }

    /**
     * Test the property 'supportingOrganizations'
     */
    @Test
    public void supportingOrganizationsTest() {
        // TODO: test supportingOrganizations
    }

    /**
     * Test the property 'coFundingPartners'
     */
    @Test
    public void coFundingPartnersTest() {
        // TODO: test coFundingPartners
    }

    /**
     * Test the property 'statesWithWork'
     */
    @Test
    public void statesWithWorkTest() {
        // TODO: test statesWithWork
    }

    /**
     * Test the property 'programDirectors'
     */
    @Test
    public void programDirectorsTest() {
        // TODO: test programDirectors
    }

    /**
     * Test the property 'programManagers'
     */
    @Test
    public void programManagersTest() {
        // TODO: test programManagers
    }

    /**
     * Test the property 'projectManagers'
     */
    @Test
    public void projectManagersTest() {
        // TODO: test projectManagers
    }

    /**
     * Test the property 'principalInvestigators'
     */
    @Test
    public void principalInvestigatorsTest() {
        // TODO: test principalInvestigators
    }

    /**
     * Test the property 'coInvestigators'
     */
    @Test
    public void coInvestigatorsTest() {
        // TODO: test coInvestigators
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'libraryItems'
     */
    @Test
    public void libraryItemsTest() {
        // TODO: test libraryItems
    }

    /**
     * Test the property 'stiDaas'
     */
    @Test
    public void stiDaasTest() {
        // TODO: test stiDaas
    }

    /**
     * Test the property 'closeoutSummary'
     */
    @Test
    public void closeoutSummaryTest() {
        // TODO: test closeoutSummary
    }

    /**
     * Test the property 'closeoutDocuments'
     */
    @Test
    public void closeoutDocumentsTest() {
        // TODO: test closeoutDocuments
    }

    /**
     * Test the property 'primaryImage'
     */
    @Test
    public void primaryImageTest() {
        // TODO: test primaryImage
    }

    /**
     * Test the property 'viewCount'
     */
    @Test
    public void viewCountTest() {
        // TODO: test viewCount
    }

}
