/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TaxonomyNode
 */
public class TaxonomyNodeTest {
    private final TaxonomyNode model = new TaxonomyNode();

    /**
     * Model tests for TaxonomyNode
     */
    @Test
    public void testTaxonomyNode() {
        // TODO: test TaxonomyNode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'taxonomyNodeId'
     */
    @Test
    public void taxonomyNodeIdTest() {
        // TODO: test taxonomyNodeId
    }

    /**
     * Test the property 'taxonomyRootId'
     */
    @Test
    public void taxonomyRootIdTest() {
        // TODO: test taxonomyRootId
    }

    /**
     * Test the property 'parentNodeId'
     */
    @Test
    public void parentNodeIdTest() {
        // TODO: test parentNodeId
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'definition'
     */
    @Test
    public void definitionTest() {
        // TODO: test definition
    }

    /**
     * Test the property 'hasChildren'
     */
    @Test
    public void hasChildrenTest() {
        // TODO: test hasChildren
    }

    /**
     * Test the property 'publishedUrl'
     */
    @Test
    public void publishedUrlTest() {
        // TODO: test publishedUrl
    }

}
