/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LkuCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Represents a specific library item.
 */
@ApiModel(description = "Represents a specific library item.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LibraryItem {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "contentType";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private LkuCode contentType;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<File> files = null;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_PUBLISHED_DATE_STRING = "publishedDateString";
  @SerializedName(SERIALIZED_NAME_PUBLISHED_DATE_STRING)
  private String publishedDateString;

  public static final String SERIALIZED_NAME_PUBLISHED_BY = "publishedBy";
  @SerializedName(SERIALIZED_NAME_PUBLISHED_BY)
  private String publishedBy;

  public LibraryItem() {
  }

  public LibraryItem title(String title) {
    
    
    
    
    this.title = title;
    return this;
  }

   /**
   * Title of the library item
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Title of the library item")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    
    
    
    this.title = title;
  }


  public LibraryItem description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Description of the library item.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the library item.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public LibraryItem id(Long id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the library item.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unique identifier for the library item.")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    
    
    
    this.id = id;
  }


  public LibraryItem contentType(LkuCode contentType) {
    
    
    
    
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LkuCode getContentType() {
    return contentType;
  }


  public void setContentType(LkuCode contentType) {
    
    
    
    this.contentType = contentType;
  }


  public LibraryItem files(List<File> files) {
    
    
    
    
    this.files = files;
    return this;
  }

  public LibraryItem addFilesItem(File filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * List of files associated with the library item.
   * @return files
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of files associated with the library item.")

  public List<File> getFiles() {
    return files;
  }


  public void setFiles(List<File> files) {
    
    
    
    this.files = files;
  }


  public LibraryItem url(String url) {
    
    
    
    
    this.url = url;
    return this;
  }

   /**
   * External URL for the library item.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "External URL for the library item.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    
    
    
    this.url = url;
  }


  public LibraryItem publishedDateString(String publishedDateString) {
    
    
    
    
    this.publishedDateString = publishedDateString;
    return this;
  }

   /**
   * Date the library item was published.
   * @return publishedDateString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date the library item was published.")

  public String getPublishedDateString() {
    return publishedDateString;
  }


  public void setPublishedDateString(String publishedDateString) {
    
    
    
    this.publishedDateString = publishedDateString;
  }


  public LibraryItem publishedBy(String publishedBy) {
    
    
    
    
    this.publishedBy = publishedBy;
    return this;
  }

   /**
   * Publisher of the library item.
   * @return publishedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Publisher of the library item.")

  public String getPublishedBy() {
    return publishedBy;
  }


  public void setPublishedBy(String publishedBy) {
    
    
    
    this.publishedBy = publishedBy;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LibraryItem instance itself
   */
  public LibraryItem putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LibraryItem libraryItem = (LibraryItem) o;
    return Objects.equals(this.title, libraryItem.title) &&
        Objects.equals(this.description, libraryItem.description) &&
        Objects.equals(this.id, libraryItem.id) &&
        Objects.equals(this.contentType, libraryItem.contentType) &&
        Objects.equals(this.files, libraryItem.files) &&
        Objects.equals(this.url, libraryItem.url) &&
        Objects.equals(this.publishedDateString, libraryItem.publishedDateString) &&
        Objects.equals(this.publishedBy, libraryItem.publishedBy)&&
        Objects.equals(this.additionalProperties, libraryItem.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, id, contentType, files, url, publishedDateString, publishedBy, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LibraryItem {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    publishedDateString: ").append(toIndentedString(publishedDateString)).append("\n");
    sb.append("    publishedBy: ").append(toIndentedString(publishedBy)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("title");
    openapiFields.add("description");
    openapiFields.add("id");
    openapiFields.add("contentType");
    openapiFields.add("files");
    openapiFields.add("url");
    openapiFields.add("publishedDateString");
    openapiFields.add("publishedBy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LibraryItem
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LibraryItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LibraryItem is not found in the empty JSON string", LibraryItem.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (jsonObj.get("files") != null && !jsonObj.get("files").isJsonNull()) {
        JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
        if (jsonArrayfiles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("files").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
          }

          // validate the optional field `files` (array)
          for (int i = 0; i < jsonArrayfiles.size(); i++) {
            File.validateJsonObject(jsonArrayfiles.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("publishedDateString") != null && !jsonObj.get("publishedDateString").isJsonNull()) && !jsonObj.get("publishedDateString").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `publishedDateString` to be a primitive type in the JSON string but got `%s`", jsonObj.get("publishedDateString").toString()));
      }
      if ((jsonObj.get("publishedBy") != null && !jsonObj.get("publishedBy").isJsonNull()) && !jsonObj.get("publishedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `publishedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("publishedBy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LibraryItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LibraryItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LibraryItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LibraryItem.class));

       return (TypeAdapter<T>) new TypeAdapter<LibraryItem>() {
           @Override
           public void write(JsonWriter out, LibraryItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LibraryItem read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LibraryItem instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LibraryItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LibraryItem
  * @throws IOException if the JSON string is invalid with respect to LibraryItem
  */
  public static LibraryItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LibraryItem.class);
  }

 /**
  * Convert an instance of LibraryItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

