/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Lookup code type further showing how the lookup codes within this type will be used.
 */
@ApiModel(description = "Lookup code type further showing how the lookup codes within this type will be used.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LkuCodeType {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_LKU_CODE_TYPE_ID = "lkuCodeTypeId";
  @SerializedName(SERIALIZED_NAME_LKU_CODE_TYPE_ID)
  private Long lkuCodeTypeId;

  public static final String SERIALIZED_NAME_CODE_TYPE = "codeType";
  @SerializedName(SERIALIZED_NAME_CODE_TYPE)
  private String codeType;

  public LkuCodeType() {
  }

  public LkuCodeType description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Description of the LKU Code Type
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the LKU Code Type")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public LkuCodeType lkuCodeTypeId(Long lkuCodeTypeId) {
    
    
    
    
    this.lkuCodeTypeId = lkuCodeTypeId;
    return this;
  }

   /**
   * Unique ID for this LKU Code Type
   * @return lkuCodeTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unique ID for this LKU Code Type")

  public Long getLkuCodeTypeId() {
    return lkuCodeTypeId;
  }


  public void setLkuCodeTypeId(Long lkuCodeTypeId) {
    
    
    
    this.lkuCodeTypeId = lkuCodeTypeId;
  }


  public LkuCodeType codeType(String codeType) {
    
    
    
    
    this.codeType = codeType;
    return this;
  }

   /**
   * Unique text code type that represents this LKU Code
   * @return codeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unique text code type that represents this LKU Code")

  public String getCodeType() {
    return codeType;
  }


  public void setCodeType(String codeType) {
    
    
    
    this.codeType = codeType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LkuCodeType instance itself
   */
  public LkuCodeType putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LkuCodeType lkuCodeType = (LkuCodeType) o;
    return Objects.equals(this.description, lkuCodeType.description) &&
        Objects.equals(this.lkuCodeTypeId, lkuCodeType.lkuCodeTypeId) &&
        Objects.equals(this.codeType, lkuCodeType.codeType)&&
        Objects.equals(this.additionalProperties, lkuCodeType.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, lkuCodeTypeId, codeType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LkuCodeType {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    lkuCodeTypeId: ").append(toIndentedString(lkuCodeTypeId)).append("\n");
    sb.append("    codeType: ").append(toIndentedString(codeType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("lkuCodeTypeId");
    openapiFields.add("codeType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LkuCodeType
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LkuCodeType.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LkuCodeType is not found in the empty JSON string", LkuCodeType.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("codeType") != null && !jsonObj.get("codeType").isJsonNull()) && !jsonObj.get("codeType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `codeType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codeType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LkuCodeType.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LkuCodeType' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LkuCodeType> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LkuCodeType.class));

       return (TypeAdapter<T>) new TypeAdapter<LkuCodeType>() {
           @Override
           public void write(JsonWriter out, LkuCodeType value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LkuCodeType read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LkuCodeType instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LkuCodeType given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LkuCodeType
  * @throws IOException if the JSON string is invalid with respect to LkuCodeType
  */
  public static LkuCodeType fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LkuCodeType.class);
  }

 /**
  * Convert an instance of LkuCodeType to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

