/*
 * TechPort
 * TechPort RESTful API
 *
 * The version of the OpenAPI document: 3.13.2
 * Contact: hq-techport@mail.nasa.gov
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.OrganizationGetInformationResponse;
import com.konfigthis.client.model.OrganizationGetListByNameResponse;
import com.konfigthis.client.model.OrganizationListTypesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationApi
 */
@Disabled
public class OrganizationApiTest {

    private static OrganizationApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new OrganizationApi(apiClient);
    }

    /**
     * Get an organization and its information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInformationTest() throws ApiException {
        Long organizationId = null;
        OrganizationGetInformationResponse response = api.getInformation(organizationId)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a list of organizations that match a given name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListByNameTest() throws ApiException {
        String name = null;
        OrganizationGetListByNameResponse response = api.getListByName()
                .name(name)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a list of available organization types, including set-aside and MSI types.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTypesTest() throws ApiException {
        OrganizationListTypesResponse response = api.listTypes()
                .execute();
        // TODO: test validations
    }

}
